### PR TITLE
Fix bug NPE in AppSyncOfflineMutationInterceptor

### PR DESCRIPTION
**Pull request by alanvan0502**
*Description of changes: Fix bug NPE in AppSyncOfflineMutationInterceptor

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kvasukib** [comment]
@alanvan0502 Thank you for this PR! My understanding about this PR is that there are two changes here: 1) Fix NPE 2) Change SqlHelpers for mutations and delta sync to be singleton objects.

I agree with (1). For (2), I have some reservations. (2) is probably one of the fixes for SQLIte Database Locked exception issues in AppSync SDK. However with PR #174 I am changing the AWSAppSyncClient architecture especially the database architecture. With PR #174, each `AWSAppSyncClient` object will have its own database based on a client database prefix passed in to the `AWSAppSyncClient` while constructing the object.

So ideally for your solution for (2), we may need to maintain a factory of objects: the SqlHelper will have a map of (database-name, SqlHelper) objects and the SqlHelper will be accessed through a singleton object by different `AWSAppSyncClient` objects.

I am discussing this approach with the team today and will have more updates around this soon. 

My plan for this PR is to isolate the NPE change for offline mutations and merge that change so we can unblock you from that bug. Let me know your thoughts on this.

**Comment by alanvan0502** [comment]
@kvasukib Thanks for the response. We agree with your approach for both (1) and (2).

**Comment by kvasukib** [comment]
@alanvan0502 Sorry for the delayed response. Can you explain how you are experiencing the `SQLiteDatabaseLockedException`? Do you have multiple `AWSAppSyncClient` objects created and are you experiencing crashes when you have multiple clients?

From my understanding of the SQLite Database in Android, Android maintains a single connection to the SQLite Database irrespective of the number of SqlHelper objects created and the number of threads that could race for the connection. This is done by Android through locking the SQLite connection in the implementation.

So I suspect how would the AppSync SDK encounter this situation?

**Comment by alanvan0502** [comment]
@kvasukib Yes the SQLiteDatabaseLockedException was experienced when I use multiple clients to improve the sync performance. Since I changed the SqlHelper to singleton, my users do not experience the crash anymore. You can refer to the screenshot attached with issue #147 for the stacktrace.

**Pull request closed without merging**
