### PR TITLE
fix(aws-android-sdk-appsync-gradle-plugin): Update plugin to support Gradle 6.0

### PR DESCRIPTION
**Pull request by jpignata**
*Issue #, if available:* #270

*Description of changes:* This is a spike on properly supporting Gradle 6.0+ by no longer calling the constructor on `DefaultSourceDirectorySet` which no longer exists. I've not tested this yet, and opening this up as a draft for feedback and thoughts and corrections on my bad reading of the API docs.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jpignata** [comment]
Would appreciate some thoughts here before I iterate. @jamesonwilliams @richardmcclellan @TrekSoft @raphkim @rjuliano

**Comment by jamesonwilliams** [comment]
> Would appreciate some thoughts here before I iterate. @jamesonwilliams @richardmcclellan @TrekSoft @raphkim @rjuliano 

Looks like a reasonable start. I also did have a solution like this. I used this Protobuf PR as a spirit guide. https://github.com/google/protobuf-gradle-plugin/pull/292/files

After getting around this issue, I next confronted problems with the NodeJS Gradle plugin being unable to download a Node distribution.

**Comment by SunnyBe** [comment]
Doesn't look like this contribution went pass the pipeline build.

**Comment by ahardin** [comment]
Any ETA on when this will be pursued again? I would be happy to test it once a beta goes out.

**Comment by TrekSoft** [comment]
We're currently in active development on it and will post an update when it's done.

**Pull request merged**
