### PR TITLE
Fix #147 - Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException

### LINKED ISSUE #147: Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException
**Describe the bug**
Database is locked when AppSyncMutationSqlCacheOperations.deleteRecord is called (see stacktrace)

**Expected behavior**
SQLiteDatabase should not throw the LockedException.

**Screenshots**
image

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.7.9

**Device Information (please complete the following information):**
 - Device: samsung, OPPO, Xiaomi, LGE
 - Android Version: 5, 6, 7, 8

### PR DESCRIPTION
**Pull request by alanvan0502**
*Issue #147 

*Description of changes: Make SQLHelpers singleton to avoid database lock exceptions. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kvasukib** [comment]
@alanvan0502 Thank you for your contribution! Can you resolve the conflicts and update the PR?

**Comment by alanvan0502** [comment]
@kvasukib would you like me to merge my branch with your aws_lab/master?

**Comment by kvasukib** [comment]
@alanvan0502 Can you sync the changes from the master to your branch and fix the conflicts?

**Comment by alanvan0502** [comment]
@kvasukib Done. For your review please. Also, I have another 2 outstanding PRs (#169 & #175). Please review them too. Thank you!

**Comment by EmilyWilson** [comment]
@alanvan0502 @kvasukib  any update on this PR? Our team has seen this crash and are wondering if this fix will become available soon?

**Comment by alanvan0502** [comment]
> @alanvan0502 @kvasukib any update on this PR? Our team has seen this crash and are wondering if this fix will become available soon?

@EmilyWilson I think in #174, AWS team has addressed this issue by allowing the option of creating a separate database for every AppSyncClient created. Just that there's also another crash (which I fixed on a separate PR. See #209 for more details). Alternatively, my fix for this PR (#147) works just fine if you only want 1 single db for your multiple clients (access to db must be synchronized though).

**Comment by EmilyWilson** [comment]
> > @EmilyWilson I think in #174, AWS team has addressed this issue by allowing the option of creating a separate database for every AppSyncClient created. Just that there's also another crash (which I fixed on a separate PR. See #209 for more details). Alternatively, my fix for this PR (#147) works just fine if you only want 1 single db for your multiple clients (access to db must be synchronized though).

@alanvan0502 thanks for your reply. That's great, I will work with those updates.

**Pull request closed without merging**
